// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB81YWlBwZntIldf0VnlGRTjhI5sxi_ycg',
    appId: '1:844847865301:web:dafd6f1e1ab4ca7b08315c',
    messagingSenderId: '844847865301',
    projectId: 'moodtunes-18650',
    authDomain: 'moodtunes-18650.firebaseapp.com',
    storageBucket: 'moodtunes-18650.appspot.com',
    measurementId: 'G-VTQQKEPVHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS4_ANRcz2DmbNfBFyZuUCbIm06fE8OaQ',
    appId: '1:844847865301:android:88e3b0a302d96da208315c',
    messagingSenderId: '844847865301',
    projectId: 'moodtunes-18650',
    storageBucket: 'moodtunes-18650.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVTUEf2_I2b7fPzIo2i7ytn6J75ElSmko',
    appId: '1:844847865301:ios:b3c28ce5797428e508315c',
    messagingSenderId: '844847865301',
    projectId: 'moodtunes-18650',
    storageBucket: 'moodtunes-18650.appspot.com',
    iosBundleId: 'com.example.moodTunes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVTUEf2_I2b7fPzIo2i7ytn6J75ElSmko',
    appId: '1:844847865301:ios:fd69da520e435a3c08315c',
    messagingSenderId: '844847865301',
    projectId: 'moodtunes-18650',
    storageBucket: 'moodtunes-18650.appspot.com',
    iosBundleId: 'com.example.moodTunes.RunnerTests',
  );
}
